name: Bot linter comment
# We need these permissions to be able to post / update comments
permissions:
  pull-requests: write
  issues: write

on:
  workflow_run:
    workflows: ["Linter"]
    types:
      - completed

jobs:
  bot-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    steps:
      - name: Create temporary artifacts directory
        run: mkdir -p ${{ runner.temp }}/artifacts

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lint-log
          path: ${{ runner.temp }}/artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: python -m pip install requests

      - name: Create/update GitHub comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_SHA: ${{ github.event.workflow_run.head_sha }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          set -e
          ARTIFACTS_DIR="${{ runner.temp }}/artifacts"
          export PR_NUMBER=$(cat $ARTIFACTS_DIR/pr_number.txt)
          export LOG_FILE="$ARTIFACTS_DIR/linting_output.txt"
          export VERSIONS_FILE="$ARTIFACTS_DIR/versions.txt"

          mkdir build_tools
          curl https://raw.githubusercontent.com/${{ github.repository }}/main/build_tools/get_comment.py \
              --retry 5 -o build_tools/get_comment.py
          python ./build_tools/get_comment.py
